[package]
name = "matrices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15.6", features = ["approx"] }
approx = "0.5.0"
nalgebra =  "0.31.4"
serde_json = "1.0.70"